CREATE TABLE `erp_stock_log` (
                                 `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
                                 `order_id` varchar(50) NOT NULL COMMENT '业务单据编号',
                                 `order_biz_code` varchar(50) NOT NULL COMMENT '业务单据批次号,一个单据会有多个批次号',
                                 `order_action` varchar(20) NOT NULL DEFAULT '' COMMENT '单据操作类型',
                                 `source_order_id` varchar(50) NOT NULL DEFAULT '' COMMENT '有品订单号',
                                 `product_id` bigint(20) NOT NULL COMMENT '商品id',
                                 `type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '库存类型 1-3c,2-汽车配件',
                                 `wh_id` int(11) NOT NULL COMMENT '仓库id',
                                 `channel` varchar(100) NOT NULL DEFAULT 'youpin' COMMENT '渠道,默认youpin',
                                 `zp` int(11) NOT NULL DEFAULT '0' COMMENT '正品变动',
                                 `cc` int(11) NOT NULL DEFAULT '0' COMMENT '残次品变动',
                                 `bk` int(11) NOT NULL DEFAULT '0' COMMENT '备件变动',
                                 `lk` int(11) NOT NULL DEFAULT '0' COMMENT '锁定变动',
                                 `zy` int(11) NOT NULL DEFAULT '0' COMMENT '占用变动',
                                 `zt` int(11) NOT NULL DEFAULT '0' COMMENT '入库在途变动',
                                 `dbzt` int(11) NOT NULL DEFAULT '0' COMMENT '调拨在途变动',
                                 `cs` int(11) NOT NULL DEFAULT '0' COMMENT '超售变动',
                                 `zc` int(11) NOT NULL DEFAULT '0' COMMENT '在仓变动',
                                 `cszt` int(11) NOT NULL DEFAULT '0' COMMENT '超售在途变动',
                                 `order_action_time` datetime NOT NULL COMMENT '单据记录更新库存时间',
                                 `remark` text COMMENT '备注',
                                 `ext` text COMMENT '记录库存更新拓展信息',
                                 `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '增加时间',
                                 `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                 `notify_ips` tinyint(1) NOT NULL DEFAULT '1' COMMENT '该库存变动ips是否需要消费,1是0否',
                                 PRIMARY KEY (`id`),
                                 KEY `order_index` (`order_id`,`order_biz_code`,`order_action`),
                                 KEY `product_index` (`product_id`,`wh_id`,`channel`),
                                 KEY `order_action_time` (`order_action_time`),
                                 KEY `order_action` (`order_action`),
                                 KEY `idx_ctime` (`create_time`),
                                 KEY `idx_source_order` (`source_order_id`),
                                 KEY `idx_type` (`type`)
) ENGINE=InnoDB AUTO_INCREMENT=65144391 DEFAULT CHARSET=utf8 COMMENT='库存单据流水表'