CREATE TABLE `erp_stock_live` (
                                  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
                                  `product_id` bigint(20) NOT NULL COMMENT '商品id',
                                  `wh_id` int(11) NOT NULL COMMENT '仓库',
                                  `channel` varchar(100) NOT NULL DEFAULT 'youpin' COMMENT '渠道,默认youpin',
                                  `name` varchar(255) NOT NULL DEFAULT '' COMMENT '商品名称',
                                  `producer_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '商家id',
                                  `type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '库存类型 1-3c,2-汽车配件',
                                  `zp` int(11) NOT NULL DEFAULT '0' COMMENT '正品',
                                  `cc` int(11) NOT NULL DEFAULT '0' COMMENT '残次品',
                                  `bk` int(11) NOT NULL DEFAULT '0' COMMENT '备件',
                                  `lk` int(11) NOT NULL DEFAULT '0' COMMENT '锁定',
                                  `cclk` int(11) NOT NULL DEFAULT '0' COMMENT '残次品锁定',
                                  `bxjjlk` int(11) NOT NULL DEFAULT '0' COMMENT '保修旧件锁定',
                                  `wxjjlk` int(11) NOT NULL DEFAULT '0' COMMENT '维修旧件锁定',
                                  `zy` int(11) NOT NULL DEFAULT '0' COMMENT '占用',
                                  `dbzy` int(11) NOT NULL DEFAULT '0' COMMENT '调拨占用',
                                  `ccdbzy` int(11) NOT NULL DEFAULT '0' COMMENT '残次品调拨占用',
                                  `bxjjdbzy` int(11) NOT NULL DEFAULT '0' COMMENT '保修旧件调拨占用',
                                  `wxjjdbzy` int(11) NOT NULL DEFAULT '0' COMMENT '维修旧件调拨占用',
                                  `llzy` int(11) NOT NULL DEFAULT '0' COMMENT '领料占用',
                                  `zt` int(11) NOT NULL DEFAULT '0' COMMENT '入库在途',
                                  `cczt` int(11) NOT NULL DEFAULT '0' COMMENT '残次品在途',
                                  `dbzt` int(11) NOT NULL DEFAULT '0' COMMENT '调拨在途',
                                  `bxjjzt` int(11) NOT NULL DEFAULT '0' COMMENT '保修旧件在途',
                                  `wxjjzt` int(11) NOT NULL DEFAULT '0' COMMENT '维修旧件在途',
                                  `cs` int(11) NOT NULL DEFAULT '0' COMMENT '超售',
                                  `zc` int(11) NOT NULL DEFAULT '0' COMMENT '在仓',
                                  `cszt` int(11) NOT NULL DEFAULT '0' COMMENT '超售在途',
                                  `bxjj` int(11) NOT NULL DEFAULT '0' COMMENT '保修旧件',
                                  `wxjj` int(11) NOT NULL DEFAULT '0' COMMENT '维修旧件',
                                  `dbys` int(11) NOT NULL DEFAULT '0' COMMENT '调拨预锁',
                                  `order_id` varchar(50) NOT NULL DEFAULT '' COMMENT '最后一次更新的order_id',
                                  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '增加时间',
                                  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                  PRIMARY KEY (`id`),
                                  UNIQUE KEY `product_id` (`product_id`,`wh_id`,`channel`),
                                  KEY `producer_id` (`producer_id`),
                                  KEY `idx_type` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商品库存明细'