@startuml
'https://plantuml.com/sequence-diagram
skin rose
autonumber

participant 调拨服务
participant 出入库服务
participant CIMS
participant RDC
participant 门店WMS
queue 事件中心

'---------------------------真实出库--------------------------'
RDC -> 出入库服务 : 真实出库
出入库服务 -> CIMS : 更新库存(实际出库)
出入库服务 <-- CIMS : 更新成功
出入库服务 -> 出入库服务 : 更新出库单("<font color=red>已出库</font>")
出入库服务 -> 出入库服务 : 更新出库单明细\n实际每个商品出了多少
出入库服务 -> 出入库服务 : 写出库单log表
出入库服务 -> 事件中心 : 发出库成功消息
出入库服务 <-- 事件中心 : 成功
出入库服务 -> RDC : 返回结果



@enduml