@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(Total, "门店/总部业务") {
    Container(CG, "采购单")
    Container(MDLL, "门店共工单领料")
    Container(MDHL, "门店共工单还料")
    Container(RGCJ, "人工创建入库单")
    Container(CPTG, "残品/退供出库")
}

System_Boundary(SCM, "SCM") {
    Container(DB, "调拨单")
    Container(CK, "出库单")
    Container(RK, "入库单")
}

System(SIMS, "库存服务")

System(RDC, "RDC仓 WMS")

System(Store, "门店 WMS")

Rel(CG, DB, "拆单", "DUBBO")
Rel(MDLL, CK, "领料", "DUBBO")
Rel(MDHL, RK, "还料", "DUBBO")
Rel(DB, CK, "创建", "DUBBO")
Rel(DB, RK, "创建", "DUBBO")
Rel(SCM, SIMS, "占用/释放", "DUBBO")
Rel(SCM, RDC, "入库/出库单通知", "HTTPS")
Rel(SCM, Store, "入库/出库单通知", "DUBBO")


@enduml