@startuml
'https://plantuml.com/state-diagram


skin rose


[*] --> 已创建 : 创建入库单
已创建 --> 已推送 : 推WMS成功
已推送 --> 部分收货 : 部分收货
部分收货 --> 全部收货 : 入库单全部收货
全部收货 --> [*]

已推送 --> 全部收货 : 全部收货

已创建 --> 取消
已推送 --> 取消

取消 --> [*]

@enduml