@startuml
'https://plantuml.com/state-diagram


skin rose

state 待推仓
state 推仓中
state 待确认
state 待出库
state 已出库
state 已取消


[*] --> 待推仓 : 创建出库单
待推仓 --> 推仓中 : 扣减库存
推仓中 --> 待出库 : 推仓成功
推仓中 --> 待确认 : 推仓成功
待确认 --> 待出库 : 仓库确认
待出库 --> 已出库 : 出库
已出库 --> [*]

待推仓 --> 已取消 : 取消出库单
待出库 --> 已取消 : 取消出库单
推仓中 --> 已取消 : 取消出库单
待确认 --> 已取消 : 取消出库单
待出库 --> 已取消 : 取消出库单

已取消 --> [*]

@enduml