package reflect;

import java.util.Date;
import java.util.List;
import java.util.Map;

public class Promotion {
    private Long promoId;
    private Long venderId;
    private String name;
    private Integer type;
    private Integer favorMode;
    private String beginTime;
    private String endTime;
    private Integer bound;
    private Integer member;
    private String slogan;
    private String comment;
    private String ext;
    private Integer srcType;
    private Long srcRfId;
    private Integer status;
    private Integer promoStatus;
    private Long rfId;
    private Date created;
    private Date modified;
    private Integer platform;
    private Integer shopMember;
    private Integer qqMember;
    private String link;
    private Map<Integer, String> platFormMap;
    private Integer plusMember;
    private Integer samMember;
    private Long tokenId;
    private List<String> promoChannelList;
    private Boolean memberLevelOnly;
    private Integer tokenUseNum;
    private String operator;
    private boolean allowOthersOperate = true;
    private boolean isJingdouRequired = false;
    private boolean allowOthersCheck = true;
    private boolean allowOtherUserOperate = true;
    private boolean allowOtherUserCheck = true;
    private Long multiShopActivityId;
    private boolean needManualCheck = true;
    private boolean allowCheck = true;
    private boolean allowOperate = true;
    private Long previewsId;
    private String previewsContent;
    private String previewsTime;
    private Long skuIconId;
    private String skuIconShowTime;
    private Integer promoAreaType;
    private List<String> promoAreaList;
    private boolean showTokenPrice = false;
    private Integer extraTag;
    private String extraId;
    private Integer shopFans;
    private Map<String, String> extMap;
    private Integer venderType = Integer.valueOf(0);
}
