@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddBoundaryTag("recycle_cron_bg", $bgColor="#F0B775", $fontColor="black", $borderColor="white", $shadowing="true", $shape = RoundedBoxShape(), $type="System Boundary")
AddBoundaryTag("outer_sys_bg", $bgColor="#fbe2b4", $fontColor="black", $borderColor="white", $shadowing="true", $shape = RoundedBoxShape(), $type="System Boundary")
AddBoundaryTag("middle_bg", $bgColor="#9baec8", $fontColor="black", $borderColor="white", $shadowing="true", $shape = RoundedBoxShape(), $type="System Boundary")
AddBoundaryTag("xinxi_tech_bg", $bgColor="#eb8b71", $fontColor="black", $borderColor="white", $shadowing="true", $shape = RoundedBoxShape(), $type="System Boundary")
AddBoundaryTag("backcend_manage_sys_bg", $bgColor="#7ca2a1", $fontColor="black", $borderColor="white", $shadowing="true", $shape = RoundedBoxShape(), $type="System Boundary")
AddBoundaryTag("backcend_manage_server_bg", $bgColor="#DFD9E2", $fontColor="black", $borderColor="white", $shadowing="true", $shape = RoundedBoxShape(), $type="System Boundary")
AddBoundaryTag("mall_bg", $bgColor="#a5dff9", $fontColor="black", $borderColor="white", $shadowing="true", $shape = RoundedBoxShape(), $type="System Boundary")

System_Boundary(recycle_middle, "换新中台", $tags="recycle_cron_bg") {
    System(mishop_recycle_crond, "Go定时任务", "发券、扣资金池、业务补偿\n拉取分类、产品、城市等信息\n同步订单信息到回收商")
    System_Boundary(recycle_management_server, "换新后台管理服务", $tags="backcend_manage_server_bg") {
        System(mishop_recycleconf, "换新产品站配置服务", "换新C端入口配置\n大家电活动配置")
        System(recycle_management, "换新管理服务", "线上【机型、分类、品牌管理、\n立减活动配置、增值服务配置】\n\n线下【门店活动、返佣返利、\n签约、质检库】")
    }
}

System_Boundary(recycle_management_backend_sys, "后台管理系统", $tags="backcend_manage_sys_bg") {
    System(bd_backend, "bd后台", "一些换新相关的配置\n作废现金券\n同步城市信息")
}

System_Boundary(middle, "零售中台", $tags="middle_bg") {
    System(cash_account, "现金账户", "扣/退款")
    System(ecard, "礼品卡", "发券")
    System(karos, "交易服务（Karos）", "查询订单")
}

System_Boundary(mall, "商城", $tags="mall_bg") {
    System(xiaomi_bingo, "xiaomi_bingo", "发奖(优惠券)")
}

System_Boundary(xinxi_tech, "信息技术部", $tags="xinxi_tech_bg") {
    System(imei, "imei", "oaid查询imei")
    System(OC, "OC", "micare查询、报案、取消报案、核销")
    System(xm_imei, "xm_imei", "作废imei")
}

System_Boundary(ouer_sys_to, "外部三方系统", $tags="outer_sys_bg") {
    System_Ext(recycler, "回收商（线上）", "爱回收/闪回收")
}

Rel(mishop_recycle_crond, ouer_sys_to, "Uses", "HTTPS")
Rel(mishop_recycle_crond, xinxi_tech, "Uses", "HTTPS")
Rel(mishop_recycle_crond, middle, "Uses", "HTTPS")
Rel(mishop_recycle_crond, mall, "Uses", "Thrift")
Rel(mishop_recycle_crond, bd_backend, "Write", "Redis")
Rel(recycle_management_server, bd_backend, "Read", "Redis/MySQL")

SHOW_LEGEND()
@enduml