@startuml
!include ../../C4_Container.puml

AddBoundaryTag("recycle_cron_bg", $bgColor="#F0B775", $fontColor="black", $borderColor="white", $shadowing="true", $shape = RoundedBoxShape(), $type="System Boundary")
AddBoundaryTag("outer_sys_bg", $bgColor="#fbe2b4", $fontColor="black", $borderColor="white", $shadowing="true", $shape = RoundedBoxShape(), $type="System Boundary")
AddBoundaryTag("middle_bg", $bgColor="#9baec8", $fontColor="black", $borderColor="white", $shadowing="true", $shape = RoundedBoxShape(), $type="System Boundary")
AddBoundaryTag("xinxi_tech_bg", $bgColor="#eb8b71", $fontColor="black", $borderColor="white", $shadowing="true", $shape = RoundedBoxShape(), $type="System Boundary")
AddBoundaryTag("finance_bg", $bgColor="#7ca2a1", $fontColor="black", $borderColor="white", $shadowing="true", $shape = RoundedBoxShape(), $type="System Boundary")

System_Boundary(recycle_middle, "换新中台", $tags="recycle_cron_bg") {
    System(recycle_cron, "换新交易新定时任务", "同步品牌、品类、订单、快递\n保值换新订单同步miboss订单信息\n照片打印订单同步至miboss\noc保值换新对账任务\n业务补偿\n线下关单\n转转token刷新\n发券、作废券\n")
}

System_Boundary(middle, "零售中台", $tags="middle_bg") {
    System(ecard, "礼品卡", "发券/作废券")
}

System_Boundary(xinxi_tech, "信息技术部", $tags="xinxi_tech_bg") {
    System(OC, "OC", "保值权益查询")
}

System_Boundary(finance, "财务部", $tags="finance_bg") {
    System(MiBoss, "MiBoss", "同步保值订单\n同步照片打印订单")
}

System_Boundary(ouer_sys_to, "外部三方系统", $tags="outer_sys_bg") {
    System_Ext(recycler, "回收商（线上）", "转转、鑫郃、转转循环")
    System_Ext(recycler_offline, "回收商（线下）", "转转、闪回收、转转循环")
}

Rel(recycle_cron, ouer_sys_to, "Uses", "HTTPS")
Rel(recycle_cron, xinxi_tech, "Uses", "HTTPS")
Rel(recycle_cron, middle, "Uses", "HTTPS")
Rel(recycle_cron, finance, "Uses", "HTTPS")

SHOW_LEGEND()
@enduml